// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WarcraftArchive.Api.Data;

#nullable disable

namespace WarcraftArchive.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260225000000_UnifyDifficultyBitmaskAndSplitLastStatus")]
    partial class UnifyDifficultyBitmaskAndSplitLastStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("ContentUserMotives", b =>
                {
                    b.Property<Guid>("ContentsId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MotivesId")
                        .HasColumnType("TEXT");

                    b.HasKey("ContentsId", "MotivesId");

                    b.HasIndex("MotivesId");

                    b.ToTable("ContentUserMotives");
                });

            modelBuilder.Entity("WarcraftArchive.Api.Models.Auth.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("WarcraftArchive.Api.Models.Auth.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WarcraftArchive.Api.Models.Auth.UserMotive", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId", "Name")
                        .IsUnique();

                    b.ToTable("UserMotives");
                });

            modelBuilder.Entity("WarcraftArchive.Api.Models.Auth.Warband", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId", "Name")
                        .IsUnique();

                    b.ToTable("Warbands");
                });

            modelBuilder.Entity("WarcraftArchive.Api.Models.Warcraft.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Covenant")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Race")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("WarbandId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("WarbandId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("WarcraftArchive.Api.Models.Warcraft.Content", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AllowedDifficulties")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Expansion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Expansion");

                    b.HasIndex("Name");

                    b.ToTable("Contents");
                });

            modelBuilder.Entity("WarcraftArchive.Api.Models.Warcraft.Tracking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContentId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Frequency")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastCompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentId");

                    b.HasIndex("Frequency");

                    b.HasIndex("Status");

                    b.HasIndex("CharacterId", "ContentId", "Difficulty")
                        .IsUnique();

                    b.ToTable("Trackings");
                });

            modelBuilder.Entity("ContentUserMotives", b =>
                {
                    b.HasOne("WarcraftArchive.Api.Models.Warcraft.Content", null)
                        .WithMany()
                        .HasForeignKey("ContentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarcraftArchive.Api.Models.Auth.UserMotive", null)
                        .WithMany()
                        .HasForeignKey("MotivesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WarcraftArchive.Api.Models.Auth.RefreshToken", b =>
                {
                    b.HasOne("WarcraftArchive.Api.Models.Auth.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WarcraftArchive.Api.Models.Auth.UserMotive", b =>
                {
                    b.HasOne("WarcraftArchive.Api.Models.Auth.User", "OwnerUser")
                        .WithMany("UserMotives")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("WarcraftArchive.Api.Models.Auth.Warband", b =>
                {
                    b.HasOne("WarcraftArchive.Api.Models.Auth.User", "OwnerUser")
                        .WithMany("Warbands")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("WarcraftArchive.Api.Models.Warcraft.Character", b =>
                {
                    b.HasOne("WarcraftArchive.Api.Models.Auth.User", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WarcraftArchive.Api.Models.Auth.Warband", "Warband")
                        .WithMany("Characters")
                        .HasForeignKey("WarbandId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("OwnerUser");

                    b.Navigation("Warband");
                });

            modelBuilder.Entity("WarcraftArchive.Api.Models.Warcraft.Tracking", b =>
                {
                    b.HasOne("WarcraftArchive.Api.Models.Warcraft.Character", "Character")
                        .WithMany("Trackings")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarcraftArchive.Api.Models.Warcraft.Content", "Content")
                        .WithMany("Trackings")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Content");
                });

            modelBuilder.Entity("WarcraftArchive.Api.Models.Auth.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserMotives");

                    b.Navigation("Warbands");
                });

            modelBuilder.Entity("WarcraftArchive.Api.Models.Auth.Warband", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("WarcraftArchive.Api.Models.Warcraft.Character", b =>
                {
                    b.Navigation("Trackings");
                });

            modelBuilder.Entity("WarcraftArchive.Api.Models.Warcraft.Content", b =>
                {
                    b.Navigation("Trackings");
                });
#pragma warning restore 612, 618
        }
    }
}
